import React, { useState, useEffect } from 'react';
import { SchoolConfig } from '../types';
import { X, Save, Sliders, RotateCcw, Calendar, MapPin, Sparkles, Building, Award, ShieldCheck, KeyRound, Check, AlertCircle } from 'lucide-react';
import { INITIAL_SCHOOL_CONFIG } from '../data/initialData';
import { getAdminPin, setAdminPin } from '../utils/authHelpers';

interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
  config: SchoolConfig;
  onSave: (newConfig: SchoolConfig) => void;
  isAdmin?: boolean;
}

export const SettingsModal: React.FC<SettingsModalProps> = ({
  isOpen,
  onClose,
  config,
  onSave,
  isAdmin = false,
}) => {
  const [formData, setFormData] = useState<SchoolConfig>(config);
  const [adminPinInput, setAdminPinInput] = useState<string>('');
  const [adminPinConfirm, setAdminPinConfirm] = useState<string>('');
  const [pinStatusMessage, setPinStatusMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  useEffect(() => {
    setFormData(config);
    setAdminPinInput('');
    setAdminPinConfirm('');
    setPinStatusMessage(null);
  }, [config, isOpen]);

  if (!isOpen) return null;

  const handleChange = (key: keyof SchoolConfig, val: string) => {
    setFormData((prev) => ({ ...prev, [key]: val }));
  };

  const handleReset = () => {
    setFormData(INITIAL_SCHOOL_CONFIG);
  };

  const handleAutoGenerateDateAr = () => {
    const place = formData.placeNameAr || 'بغونتونج سندور';
    const masehi = formData.dateMasehi || '٢٥ سبتمبر ٢٠٢٦';
    const hijri = formData.dateHijri || '١٤ ربيع الأول ١٤٤٨';
    const formatted = `تحريرا ${place}، ${masehi} / ${hijri}`;
    setFormData((prev) => ({ ...prev, dateTextAr: formatted }));
  };

  const handleSavePin = () => {
    setPinStatusMessage(null);
    if (!adminPinInput) {
      setPinStatusMessage({ type: 'error', text: 'Masukkan PIN baru minimal 6 digit.' });
      return;
    }
    if (adminPinInput.length < 6) {
      setPinStatusMessage({ type: 'error', text: 'PIN minimal 6 digit/karakter.' });
      return;
    }
    if (adminPinInput !== adminPinConfirm) {
      setPinStatusMessage({ type: 'error', text: 'Konfirmasi PIN tidak cocok.' });
      return;
    }
    const res = setAdminPin(adminPinInput);
    if (res.success) {
      setPinStatusMessage({ type: 'success', text: 'PIN Administrator berhasil diperbarui!' });
      setAdminPinInput('');
      setAdminPinConfirm('');
    } else {
      setPinStatusMessage({ type: 'error', text: res.message });
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (adminPinInput && adminPinConfirm) {
      handleSavePin();
    }
    onSave(formData);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-xs p-4 overflow-y-auto">
      <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full my-8 overflow-hidden border border-stone-200">
        {/* Header */}
        <div className="px-6 py-4 bg-stone-800 text-white flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sliders size={18} className="text-emerald-400" />
            <h3 className="font-bold text-base">Pengaturan Raport, Judul & Tanggal Penetapan</h3>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1 text-stone-300 hover:text-white rounded-lg hover:bg-stone-700 transition"
          >
            <X size={20} />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-6 space-y-6 max-h-[80vh] overflow-y-auto text-xs">
          {/* Section 1: Nama Raport & Lembaga */}
          <div className="bg-stone-50 border border-stone-200 rounded-xl p-4 space-y-3">
            <div className="flex items-center gap-1.5 text-stone-800 font-bold text-xs uppercase tracking-wide border-b border-stone-200 pb-2">
              <Award size={15} className="text-emerald-600" />
              <span>Nama & Judul Raport</span>
            </div>

            <div>
              <label className="block font-bold text-stone-700 uppercase mb-1">
                Nama Raport (Latin / Indonesia)
              </label>
              <input
                type="text"
                value={formData.subTitleId}
                onChange={(e) => handleChange('subTitleId', e.target.value)}
                placeholder="PENILAIAN TENGAH SEMESTER GANJIL TAHUN PELAJARAN 2026-2027"
                className="w-full px-3 py-2 border border-stone-300 rounded-lg font-bold text-stone-800 focus:ring-2 focus:ring-emerald-500 bg-white"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block font-bold text-stone-700 uppercase mb-1">
                  Judul Utama Raport (Arab)
                </label>
                <input
                  type="text"
                  value={formData.titleAr}
                  onChange={(e) => handleChange('titleAr', e.target.value)}
                  className="w-full px-3 py-2 border border-stone-300 rounded-lg font-arabic text-sm text-right focus:ring-2 focus:ring-emerald-500 bg-white"
                />
              </div>

              <div>
                <label className="block font-bold text-stone-700 uppercase mb-1">
                  Subjudul Raport (Arab)
                </label>
                <input
                  type="text"
                  value={formData.subTitleAr}
                  onChange={(e) => handleChange('subTitleAr', e.target.value)}
                  className="w-full px-3 py-2 border border-stone-300 rounded-lg font-arabic text-sm text-right focus:ring-2 focus:ring-emerald-500 bg-white"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
              <div>
                <label className="block font-bold text-stone-700 uppercase mb-1">
                  Nama Yayasan / Lembaga
                </label>
                <input
                  type="text"
                  value={formData.institutionName}
                  onChange={(e) => handleChange('institutionName', e.target.value)}
                  className="w-full px-3 py-2 border border-stone-300 rounded-lg focus:ring-2 focus:ring-emerald-500 bg-white font-medium"
                />
              </div>

              <div>
                <label className="block font-bold text-stone-700 uppercase mb-1">
                  Nama Pondok Pesantren
                </label>
                <input
                  type="text"
                  value={formData.schoolName}
                  onChange={(e) => handleChange('schoolName', e.target.value)}
                  className="w-full px-3 py-2 border border-stone-300 rounded-lg focus:ring-2 focus:ring-emerald-500 bg-white font-medium"
                />
              </div>
            </div>
          </div>

          {/* Section 2: Tanggal Penetapan Raport (Editable) */}
          <div className="bg-emerald-50/60 border border-emerald-200 rounded-xl p-4 space-y-3">
            <div className="flex items-center justify-between border-b border-emerald-200 pb-2">
              <div className="flex items-center gap-1.5 text-emerald-900 font-bold text-xs uppercase tracking-wide">
                <Calendar size={15} className="text-emerald-700" />
                <span>Tanggal & Tempat Penetapan Raport</span>
              </div>
              <button
                type="button"
                onClick={handleAutoGenerateDateAr}
                className="flex items-center gap-1 text-[11px] font-bold text-emerald-700 hover:text-emerald-800 bg-emerald-100 hover:bg-emerald-200 px-2 py-0.5 rounded transition"
                title="Susun kalimat tanggal Arab otomatis dari kolom di bawah"
              >
                <Sparkles size={12} />
                Susun Teks Arab
              </button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block font-bold text-stone-700 uppercase mb-1 flex items-center gap-1">
                  <MapPin size={12} className="text-stone-500" />
                  Tempat Penetapan (Latin)
                </label>
                <input
                  type="text"
                  value={formData.placeNameLatin || ''}
                  onChange={(e) => handleChange('placeNameLatin', e.target.value)}
                  placeholder="Gunung Sindur"
                  className="w-full px-3 py-2 border border-stone-300 rounded-lg bg-white font-medium focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              <div>
                <label className="block font-bold text-stone-700 uppercase mb-1">
                  Tempat Penetapan (Arab)
                </label>
                <input
                  type="text"
                  value={formData.placeNameAr || ''}
                  onChange={(e) => handleChange('placeNameAr', e.target.value)}
                  placeholder="بغونتونج سندور"
                  className="w-full px-3 py-2 border border-stone-300 rounded-lg font-arabic text-sm text-right bg-white focus:ring-2 focus:ring-emerald-500"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block font-bold text-stone-700 uppercase mb-1">
                  Tanggal Masehi Penetapan
                </label>
                <input
                  type="text"
                  value={formData.dateMasehi || ''}
                  onChange={(e) => handleChange('dateMasehi', e.target.value)}
                  placeholder="25 September 2026"
                  className="w-full px-3 py-2 border border-stone-300 rounded-lg bg-white font-medium focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              <div>
                <label className="block font-bold text-stone-700 uppercase mb-1">
                  Tanggal Hijriyah Penetapan
                </label>
                <input
                  type="text"
                  value={formData.dateHijri || ''}
                  onChange={(e) => handleChange('dateHijri', e.target.value)}
                  placeholder="14 Rabiul Awwal 1448"
                  className="w-full px-3 py-2 border border-stone-300 rounded-lg bg-white font-medium focus:ring-2 focus:ring-emerald-500"
                />
              </div>
            </div>

            <div>
              <label className="block font-bold text-stone-700 uppercase mb-1">
                Kalimat Tanggal Raport Lengkap (Arab — Tercetak di Raport)
              </label>
              <input
                type="text"
                value={formData.dateTextAr}
                onChange={(e) => handleChange('dateTextAr', e.target.value)}
                placeholder="تحريرا بغونتونج سندور، ٢٥ سبتمبر ٢٠٢٦ / ١٤ ربيع الأول ١٤٤٨"
                className="w-full px-3 py-2 border border-emerald-300 rounded-lg font-arabic text-sm text-right bg-white focus:ring-2 focus:ring-emerald-500 font-bold"
              />
              <span className="text-[10px] text-stone-500 mt-0.5 block">
                Contoh: تحريرا بغونتونج سندور، ٢٥ سبتمبر ٢٠٢٦ / ١٤ ربيع الأول ١٤٤٨
              </span>
            </div>
          </div>

          {/* Section 3: Tahun Ajaran & Kelas */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 border-t border-stone-200 pt-4">
            <div>
              <label className="block font-bold text-stone-700 uppercase mb-1">
                Tahun Ajaran (Latin)
              </label>
              <input
                type="text"
                value={formData.academicYearLatin}
                onChange={(e) => handleChange('academicYearLatin', e.target.value)}
                placeholder="2026-2027"
                className="w-full px-3 py-2 border border-stone-300 rounded-lg font-bold focus:ring-2 focus:ring-emerald-500"
              />
            </div>

            <div>
              <label className="block font-bold text-stone-700 uppercase mb-1">
                Tahun Ajaran (Arab)
              </label>
              <input
                type="text"
                value={formData.academicYearAr}
                onChange={(e) => handleChange('academicYearAr', e.target.value)}
                placeholder="٢٠٢٦ / ٢٠٢٧"
                className="w-full px-3 py-2 border border-stone-300 rounded-lg font-arabic text-sm text-right focus:ring-2 focus:ring-emerald-500"
              />
            </div>

            <div>
              <label className="block font-bold text-stone-700 uppercase mb-1">
                Kelas (Latin)
              </label>
              <input
                type="text"
                value={formData.classLatin}
                onChange={(e) => handleChange('classLatin', e.target.value)}
                className="w-full px-3 py-2 border border-stone-300 rounded-lg font-medium focus:ring-2 focus:ring-emerald-500"
              />
            </div>

            <div>
              <label className="block font-bold text-stone-700 uppercase mb-1">
                Kelas (Arab)
              </label>
              <input
                type="text"
                value={formData.classAr}
                onChange={(e) => handleChange('classAr', e.target.value)}
                className="w-full px-3 py-2 border border-stone-300 rounded-lg font-arabic text-sm text-right focus:ring-2 focus:ring-emerald-500"
              />
            </div>
          </div>

          {/* Section 4: Signatures */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 border-t border-stone-200 pt-4">
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="block font-bold text-stone-700 uppercase">
                  Nama Wali Kelas (dengan Gelar)
                </label>
                <span className="text-[10px] font-bold px-1.5 py-0.5 bg-emerald-100 text-emerald-800 rounded">
                  {formData.classLatin || 'Kelas Aktif'}
                </span>
              </div>
              <input
                type="text"
                value={formData.waliKelasName}
                onChange={(e) => handleChange('waliKelasName', e.target.value)}
                className="w-full px-3 py-2 border border-stone-300 rounded-lg font-bold focus:ring-2 focus:ring-emerald-500"
              />
              <span className="text-[10px] text-stone-500 mt-1 block leading-tight">
                Disesuaikan otomatis per kelas (tidak permanen). Mengubah nama ini akan disimpan khusus untuk kelas <strong className="text-emerald-700">{formData.classLatin || 'ini'}</strong>.
              </span>
            </div>

            <div>
              <label className="block font-bold text-stone-700 uppercase mb-1">
                Nama Direktur Pondok / Mudir
              </label>
              <input
                type="text"
                value={formData.direkturName}
                onChange={(e) => handleChange('direkturName', e.target.value)}
                className="w-full px-3 py-2 border border-stone-300 rounded-lg font-bold focus:ring-2 focus:ring-emerald-500"
              />
              <span className="text-[10px] text-stone-500 mt-0.5 block">
                Ditampilkan di posisi tengah bawah raport
              </span>
            </div>
          </div>

          {/* Section 5: Keamanan & PIN Administrator */}
          <div className="border-t border-stone-200 pt-4 space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <ShieldCheck size={16} className="text-amber-600" />
                <h4 className="font-bold text-stone-800 text-xs uppercase tracking-wide">
                  Keamanan & PIN Administrator
                </h4>
              </div>
              <span className="text-[11px] text-stone-500">
                PIN Saat Ini: <strong className="font-mono">{getAdminPin()}</strong>
              </span>
            </div>

            <div className="p-3 bg-stone-50 rounded-xl border border-stone-200 space-y-3">
              <p className="text-[11px] text-stone-600">
                Ganti PIN masuk khusus Administrator. Minimal 6 karakter / digit angka.
              </p>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-[11px] font-bold text-stone-600 mb-1">
                    PIN Administrator Baru (Min 6 digit)
                  </label>
                  <input
                    type="password"
                    value={adminPinInput}
                    onChange={(e) => setAdminPinInput(e.target.value)}
                    placeholder="Contoh: 123456"
                    className="w-full px-3 py-1.5 border border-stone-300 rounded-lg bg-white font-mono text-sm focus:ring-2 focus:ring-amber-500"
                  />
                </div>

                <div>
                  <label className="block text-[11px] font-bold text-stone-600 mb-1">
                    Konfirmasi PIN Baru
                  </label>
                  <input
                    type="password"
                    value={adminPinConfirm}
                    onChange={(e) => setAdminPinConfirm(e.target.value)}
                    placeholder="Ketik ulang PIN baru"
                    className="w-full px-3 py-1.5 border border-stone-300 rounded-lg bg-white font-mono text-sm focus:ring-2 focus:ring-amber-500"
                  />
                </div>
              </div>

              {pinStatusMessage && (
                <div
                  className={`flex items-center gap-2 p-2 rounded-lg text-xs ${
                    pinStatusMessage.type === 'success'
                      ? 'bg-emerald-50 text-emerald-800 border border-emerald-200'
                      : 'bg-rose-50 text-rose-800 border border-rose-200'
                  }`}
                >
                  {pinStatusMessage.type === 'success' ? (
                    <Check size={14} className="text-emerald-600 shrink-0" />
                  ) : (
                    <AlertCircle size={14} className="text-rose-600 shrink-0" />
                  )}
                  <span>{pinStatusMessage.text}</span>
                </div>
              )}

              {adminPinInput && adminPinConfirm && (
                <button
                  type="button"
                  onClick={handleSavePin}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold bg-amber-600 hover:bg-amber-700 text-white rounded-lg transition shadow-sm"
                >
                  <KeyRound size={13} />
                  <span>Terapkan PIN Baru Sekarang</span>
                </button>
              )}
            </div>
          </div>

          {/* Footer Buttons */}
          <div className="flex items-center justify-between pt-4 border-t border-stone-200">
            <button
              type="button"
              onClick={handleReset}
              className="flex items-center gap-1 text-stone-500 hover:text-stone-700 transition"
            >
              <RotateCcw size={13} />
              Reset Default PTS 2026-2027
            </button>

            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 text-stone-600 hover:bg-stone-100 rounded-lg transition"
              >
                Batal
              </button>
              <button
                type="submit"
                className="flex items-center gap-1.5 px-5 py-2 font-bold bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg shadow-sm transition"
              >
                <Save size={14} />
                Simpan Perubahan
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};

